services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres-logs:/var/log/postgresql
    networks:
      - scu-network

  redis:
    image: redis:8.8.3-alpine3.23
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - scu-network

  migrations:
    image: ghcr.io/jackc/tern:latest
    container_name: postgres-migrations
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    command: migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - scu-network

  api-gateway:
    build:
      context: .
      dockerfile: ./deployments/docker/Dockerfile.api_gateway
    container_name: api-gateway
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    read_only: true
    security_opt:
      - no-new-privileges:true
    expose:
      - "8080"
    volumes:
      - ./log:/app/log
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://127.0.0.1:8080/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - scu-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  scu-network:
    driver: bridge
