// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: api/proto/generator/generator.proto

package generatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Generator_Generate1_FullMethodName = "/generator.Generator/Generate1"
	Generator_GenerateN_FullMethodName = "/generator.Generator/GenerateN"
)

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneratorClient interface {
	Generate1(ctx context.Context, in *Generate1Request, opts ...grpc.CallOption) (*Generate1Response, error)
	GenerateN(ctx context.Context, in *GenerateNRequest, opts ...grpc.CallOption) (*GenerateNResponse, error)
}

type generatorClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorClient(cc grpc.ClientConnInterface) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) Generate1(ctx context.Context, in *Generate1Request, opts ...grpc.CallOption) (*Generate1Response, error) {
	out := new(Generate1Response)
	err := c.cc.Invoke(ctx, Generator_Generate1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorClient) GenerateN(ctx context.Context, in *GenerateNRequest, opts ...grpc.CallOption) (*GenerateNResponse, error) {
	out := new(GenerateNResponse)
	err := c.cc.Invoke(ctx, Generator_GenerateN_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorServer is the server API for Generator service.
// All implementations must embed UnimplementedGeneratorServer
// for forward compatibility
type GeneratorServer interface {
	Generate1(context.Context, *Generate1Request) (*Generate1Response, error)
	GenerateN(context.Context, *GenerateNRequest) (*GenerateNResponse, error)
	mustEmbedUnimplementedGeneratorServer()
}

// UnimplementedGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedGeneratorServer struct {
}

func (UnimplementedGeneratorServer) Generate1(context.Context, *Generate1Request) (*Generate1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate1 not implemented")
}
func (UnimplementedGeneratorServer) GenerateN(context.Context, *GenerateNRequest) (*GenerateNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateN not implemented")
}
func (UnimplementedGeneratorServer) mustEmbedUnimplementedGeneratorServer() {}

// UnsafeGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratorServer will
// result in compilation errors.
type UnsafeGeneratorServer interface {
	mustEmbedUnimplementedGeneratorServer()
}

func RegisterGeneratorServer(s grpc.ServiceRegistrar, srv GeneratorServer) {
	s.RegisterService(&Generator_ServiceDesc, srv)
}

func _Generator_Generate1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Generate1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).Generate1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Generator_Generate1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).Generate1(ctx, req.(*Generate1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generator_GenerateN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GenerateN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Generator_GenerateN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GenerateN(ctx, req.(*GenerateNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Generator_ServiceDesc is the grpc.ServiceDesc for Generator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Generator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "generator.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate1",
			Handler:    _Generator_Generate1_Handler,
		},
		{
			MethodName: "GenerateN",
			Handler:    _Generator_GenerateN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/generator/generator.proto",
}
