// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v7.36.2
// source: api/proto/generator/generator.proto

package generatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Generate1Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType string                 `protobuf:"bytes,1,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	Text             string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId           int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Generate1Request) Reset() {
	*x = Generate1Request{}
	mi := &file_api_proto_generator_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate1Request) ProtoMessage() {}

func (x *Generate1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate1Request.ProtoReflect.Descriptor instead.
func (*Generate1Request) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_generator_proto_rawDescGZIP(), []int{0}
}

func (x *Generate1Request) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *Generate1Request) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Generate1Request) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Generate1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generate1Response) Reset() {
	*x = Generate1Response{}
	mi := &file_api_proto_generator_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate1Response) ProtoMessage() {}

func (x *Generate1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate1Response.ProtoReflect.Descriptor instead.
func (*Generate1Response) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_generator_proto_rawDescGZIP(), []int{1}
}

func (x *Generate1Response) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GenerateNRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NotificationTypes []string               `protobuf:"bytes,1,rep,name=notification_types,json=notificationTypes,proto3" json:"notification_types,omitempty"`
	Number            int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	UserIds           []int64                `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateNRequest) Reset() {
	*x = GenerateNRequest{}
	mi := &file_api_proto_generator_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNRequest) ProtoMessage() {}

func (x *GenerateNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNRequest.ProtoReflect.Descriptor instead.
func (*GenerateNRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_generator_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateNRequest) GetNotificationTypes() []string {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

func (x *GenerateNRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GenerateNRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GenerateNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNResponse) Reset() {
	*x = GenerateNResponse{}
	mi := &file_api_proto_generator_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNResponse) ProtoMessage() {}

func (x *GenerateNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_generator_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNResponse.ProtoReflect.Descriptor instead.
func (*GenerateNResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_generator_generator_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateNResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_api_proto_generator_generator_proto protoreflect.FileDescriptor

var file_api_proto_generator_generator_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x6c, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2b,
	0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x74, 0x0a, 0x10, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x12, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x9b,
	0x01, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x46, 0x0a, 0x09,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x31, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x4e, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a, 0x43,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x69, 0x6d, 0x75, 0x72,
	0x31, 0x34, 0x31, 0x34, 0x2f, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x43, 0x61, 0x74, 0x63, 0x68,
	0x2d, 0x55, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x3b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_generator_generator_proto_rawDescOnce sync.Once
	file_api_proto_generator_generator_proto_rawDescData = file_api_proto_generator_generator_proto_rawDesc
)

func file_api_proto_generator_generator_proto_rawDescGZIP() []byte {
	file_api_proto_generator_generator_proto_rawDescOnce.Do(func() {
		file_api_proto_generator_generator_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_generator_generator_proto_rawDescData)
	})
	return file_api_proto_generator_generator_proto_rawDescData
}

var file_api_proto_generator_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_generator_generator_proto_goTypes = []any{
	(*Generate1Request)(nil),  // 0: generator.Generate1Request
	(*Generate1Response)(nil), // 1: generator.Generate1Response
	(*GenerateNRequest)(nil),  // 2: generator.GenerateNRequest
	(*GenerateNResponse)(nil), // 3: generator.GenerateNResponse
}
var file_api_proto_generator_generator_proto_depIdxs = []int32{
	0, // 0: generator.Generator.Generate1:input_type -> generator.Generate1Request
	2, // 1: generator.Generator.GenerateN:input_type -> generator.GenerateNRequest
	1, // 2: generator.Generator.Generate1:output_type -> generator.Generate1Response
	3, // 3: generator.Generator.GenerateN:output_type -> generator.GenerateNResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_generator_generator_proto_init() }
func file_api_proto_generator_generator_proto_init() {
	if File_api_proto_generator_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_generator_generator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_generator_generator_proto_goTypes,
		DependencyIndexes: file_api_proto_generator_generator_proto_depIdxs,
		MessageInfos:      file_api_proto_generator_generator_proto_msgTypes,
	}.Build()
	File_api_proto_generator_generator_proto = out.File
	file_api_proto_generator_generator_proto_rawDesc = nil
	file_api_proto_generator_generator_proto_goTypes = nil
	file_api_proto_generator_generator_proto_depIdxs = nil
}
