create type notification_type_enum as enum (
    'friend_request',
    'friend_request_accepted',
    'new_subscriber',
    'friend_invitation',
    'found_acquaintance',
    'recommended_acquaintance',
    'friend_birthday',
    'gift',
    'like',
    'reaction_on_post',
    'reaction_on_photo',
    'reaction_on_video',
    'reaction_on_story',
    'reaction_on_comment',
    'reaction_on_product',
    'repost',
    'comment_on_post',
    'comment_on_photo',
    'comment_on_video',
    'comment_on_article',
    'comment_on_product',
    'reply_to_comment',
    'author_mention',
    'user_mention',
    'photo_tag',
    'post_mention',
    'comment_mention',
    'story_mention',
    'discussion_mention',
    'story_question',
    'story_answer',
    'new_post',
    'new_photo',
    'new_story',
    'new_video',
    'new_clip',
    'new_audio',
    'new_album',
    'new_podcast',
    'new_playlist',
    'stream_started',
    'new_author_content',
    'new_community_content',
    'community_invitation',
    'join_request_accepted',
    'role_changed',
    'co_owner_status_changed',
    'new_community_subscriber',
    'suggested_post',
    'community_comment',
    'community_reaction',
    'product_comment',
    'product_review',
    'review_published',
    'review_rejected',
    'order_status_changed',
    'abandoned_cart_reminder',
    'delivery_info',
    'money_request',
    'money_transfer',
    'balance_changed',
    'payment_state_changed',
    'subscription_purchased',
    'subscription_renewed',
    'payment_error',
    'account_changed',
    'data_verification',
    'phone_linked',
    'phone_unlinked',
    'email_linked',
    'email_unlinked',
    'security_warning',
    'access_restricted',
    'access_restored',
    'event_starting_soon',
    'call_starting_soon',
    'birthday_reminder',
    'saved_wish_reminder',
    'people_recommendation',
    'communities_recommendation',
    'publications_recommendation',
    'return_to_content_reminder',
    'support_reply',
    'app_notification',
    'service_notification',
    'game_achievement',
    'promo_selection',
    'new_feature_offer'
);

create type cluster_type_enum as enum (
    'friends_and_subscriptions',
    'content_reactions',
    'comments_and_replies',
    'mentions_and_tags',
    'new_publications_and_media',
    'communities_and_management',
    'shop_and_orders',
    'payments_and_subscriptions',
    'security_and_account_state',
    'events_reminders_and_recommendations',
    'service_and_promo_messages'
);

create type block_status_enum as enum (
    'ready',
    'summarising',
    'collecting',
    'created'
);

---- create above / drop below ----

drop type block_status_enum;

drop type cluster_type_enum;

drop type notification_type_enum;
