syntax = "proto3";

package auth;

option go_package = "github.com/Timur1414/Smart-Catch-Up/api/proto/auth;authpb";

service Auth {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
  rpc IsAuth(IsAuthRequest) returns (IsAuthResponse);
  rpc Login2FA(Login2FARequest) returns (Login2FAResponse);
  rpc Setup2FA(Setup2FARequest) returns (Setup2FAResponse);
  rpc Enable2FA(Enable2FARequest) returns (Enable2FAResponse);
  rpc Disable2FA(Disable2FARequest) returns (Disable2FAResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string confirm_password = 3;
}

message RegisterResponse {
  int64 user_id = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  int64 user_id = 1;
  string access_token = 2;
  string refresh_token = 3;
  bool mfa_required = 4;
  string temp_token = 5;
}

message RefreshRequest {
  string refresh_token = 1;
}

message RefreshResponse {
  int64 user_id = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message LogoutRequest {
  int64 user_id = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message LogoutResponse {
  bool success = 1;
}

message IsAuthRequest {
  string access_token = 1;
}

message IsAuthResponse {
  bool is_auth = 1;
  int64 user_id = 2;
}

message Login2FARequest {
  string temp_token = 1;
  string code = 2;
}

message Login2FAResponse {
  int64 user_id = 1;
  string access_token = 2;
  string refresh_token = 3;
}

message Setup2FARequest {
  int64 user_id = 1;
}

message Setup2FAResponse {
  string secret = 1;
  string otpauth_url = 2;
}

message Enable2FARequest {
  int64 user_id = 1;
  string code = 2;
}

message Enable2FAResponse {
  bool success = 1;
  repeated string backup_codes = 2;
}

message Disable2FARequest {
  int64 user_id = 1;
  string code = 2;
}

message Disable2FAResponse {
  bool success = 1;
}
